### ISSUE TITLE
zplugin mishandles paths with spaces in them

### ISSUE THREAD

**Issue by agkozak** [zdharma/zinit#223]
**Describe the bug**
In MSYS2, Cygwin, and WSL there are usually `PATH` elements with spaces in them, e.g.

    /mnt/c/Program Files/Oracle/VirtualBox

If I run a `zplugin report`, e.g. `zplugin report zdharma/zbrowse`, the report acts as if those `PATH` elements have been added by the plugin in question:

![image](https://user-images.githubusercontent.com/7599319/70363170-2a007980-183c-11ea-8c84-ee01e8413c62.png)

In fact, if I run `zplugin report --all`, every plugin's report says that it has added all of the `PATH` elements with spaces in them. If I run `zplugin unload zdharma/zbrowse`, some of the path elements with spaces in them are removed from the path (it looks as if the ones with `(x86)` in them are spared -- something to do with the parentheses?).

![image](https://user-images.githubusercontent.com/7599319/70363351-dfcbc800-183c-11ea-8781-1354fc8e7337.png)

The same thing happens if any element of `FPATH` has a space in it.

**To Reproduce**
You do not actually have to be running Windows for this to happen. On Linux, for example, if you run

    PATH+=':/foo bar'

you'll see that path element show up as a `PATH` element in zplugin reports, just as if every plugin had added it, and if you `unload` any plugin, the `unload`ing process will eliminate that element from the `PATH`.

**Expected behavior**
`zplugin` should be able to quote `PATH` elements with spaces in them in such a way that they are treated like any other `PATH` elements. They should not be reported as having been added by plugins and they should not be removed when `unload`ing plugins.

**Versions:**
 - $ZSH_VERSION == v5+
 - Operating system name and version (uname -a):
   - `MSYS_NT-10.0-18363 Sophronios 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys`
   - `CYGWIN_NT-10.0 Sophronios 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin`
   - `Linux Sophronios 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux` (WSL)
   - and, as I mentioned, presumably any system that has `PATH` elements with spaces in them -- they're just less common on Linux/BSD/Unix/etc.

**Comment by psprint** [comment]
Thanks for the report, I'll fix it soon.

**Comment by psprint** [comment]
The bug should be fixed now.

**Comment by agkozak** [comment]
I'm still getting this sort of thing

![image](https://user-images.githubusercontent.com/7599319/74211688-e19f7680-4c45-11ea-8adc-d0dba5ed8d42.png)

on MSYS2, Cygwin, and WSL.

**Comment by psprint** [comment]
The issue should be fixed now.
