### ISSUE TITLE
Some ices are ignored when using @zinit-scheduler burst

### ISSUE THREAD

**Issue by pschmitt** [zdharma/zinit#401]
**Describe the bug**
When calling `@zinit-scheduler burst` some ices seem to be ignored. In an interactive session everything works as expected though.

**To Reproduce**
Given the following config:
```
zinit light-mode lucid depth"3" wait as"command" \
       make'!' \
       atclone'./direnv hook zsh > zhook.zsh' \
       atpull'%atclone' sbin'direnv' \
       src'zhook.zsh' \
  for direnv/direnv
```
The following works:

```zsh
zi delete -y direnv/direnv
NO_INSTANT_PROMPT=1 zsh

Downloading direnv/direnv…

Cloning into '/home/pschmitt/.local/share/zinit/plugins/direnv---direnv'...
▹▸▹▹▹ ███████████ OBJ: 100, PACK: 191/191, COMPR: 100%, REC: 100%, RES: 100%  
make: Entering directory '/home/pschmitt/.local/share/zinit/plugins/direnv---direnv'
cat stdlib.sh | ./script/str2go main StdLib stdlib.sh > stdlib.go
go build  -o direnv
make: Leaving directory '/home/pschmitt/.local/share/zinit/plugins/direnv---direnv'
bin-gem-node annex: Created the direnv shim and set +x on the direnv binary
```

But this results in `make` not being called: 

```
zi delete -y direnv/direnv
NO_INSTANT_PROMPT=1 zsh -ic "@zinit-scheduler burst"

Downloading direnv/direnv…

Cloning into '/home/pschmitt/.local/share/zinit/plugins/direnv---direnv'...
◤ ███████████ OBJ: 100, PACK: 191/191, COMPR: 100%, REC: 100%, RES: 100%  
bin-gem-node annex: Warning: The sbin'' ice (`direnv') didn't match any files
.zinit-load-plugin:source:60: no such file or directory: /home/pschmitt/.local/share/zinit/plugins/direnv---direnv/zhook.zsh
_direnv_hook:2: no such file or directory: /home/pschmitt/.local/share/zinit/plugins/direnv---direnv/direnv
```

**Expected behavior**
No ice should be ignored when invoking `@zinit-scheduler burst`

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Versions:**
 - $ZSH_VERSION == 5.8
 - Operating system name and version (uname -a): `Linux fnuc 5.7.14-200.fc32.x86_64 #1 SMP Fri Aug 7 23:16:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
Similarly to the `make` example above, the `atclone` ice is affected as well as of c59ca3fa631d0adf80564515c4ebc4e3a2d42869

**Comment by psprint** [comment]
I believe the issue self-resolved by now.

**Comment by pschmitt** [comment]
No, sadly it did not. I'm on 9d7b25a1fc15d8caa395617808078760a0c98a82 and the issue is still here.

**Comment by ddnexus** [comment]
Important reference: the `@zinit-scheduler burst` works and executes all the ices, but must be called with:

```zsh
env TERM="${TERM}" zsh -isc "@zinit-scheduler burst"
``` 
More details in #484
