### ISSUE TITLE
`+zinit-message` no longer supports `%F{...}` format

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zinit#448]
**Describe the bug**
`+zinit-message` previously supported expanding `%F{}` however it seems this was broken. It can be seen during parallel updates:
`Spawning the next 15 concurrent update jobs ({191}snippets)`

**To Reproduce**
An example
```
$ +zinit-message "%F{199}test"
{199}test
$ # No color is shown
```
It seems that if you escape `%` the color is correctly expanded however the escape character is passed as well:
```
$ +zinit-message "\%F{199}test"
\test
$ # Color is shown
```

**Expected behavior**
+zinit-message should color %F{} correctly

**Screenshots**
![Screenshot 2020-12-16 12:29:06](https://user-images.githubusercontent.com/15698885/102384150-62cc4600-3f9a-11eb-9b6f-665c1960dc82.png)

**Versions:**
 - $ZSH_VERSION == `5.8`
 - Operating system name and version (uname -a): `Linux Nicks-Laptop 5.9.0-4-amd64 #1 SMP Debian 5.9.11-1 (2020-11-27) x86_64 GNU/Linux`

**Comment by psprint** [comment]
It should be fixed, thanks.

**Comment by NICHOLAS85** [comment]
Seems this was broken again in recent updates

**Comment by xfzv** [comment]
@psprint  Any update on this? it's still occurring

![Screenshot-2021-08-02T22:44:38](https://user-images.githubusercontent.com/78810647/127922000-5ac373a7-714c-4830-9a0f-341622dd3ffa.png)
